# Writes docs/FROM-MIPS.md: which files of the Hallym MIPS edition's electron/ (v2.8.0) are here
# unchanged, which changed, which were not brought, which are new.
#
#   python3 tools/from-mips.py <a checkout of ars2323/hallym-mips-simulator at v2.8.0>
import os,hashlib,sys
from collections import OrderedDict
M=os.path.join(sys.argv[1],'electron'); R=os.path.join(os.path.dirname(__file__),'..')
skip=('node_modules','build','test-results','dist','report','docs/screens')  # each edition's own pictures
def files(root):
    out=set()
    for d,_,fs in os.walk(root):
        rel=os.path.relpath(d,root)
        if rel.startswith(skip) or '/node_modules' in d: continue
        for f in fs: out.add(os.path.normpath(os.path.join(rel,f)))
    return out
m=files(M); r=files(R)-{'docs/FROM-MIPS.md'}
h=lambda p: hashlib.sha256(open(p,'rb').read()).hexdigest()
same=sorted(f for f in m&r if h(os.path.join(M,f))==h(os.path.join(R,f)))
changed=sorted(f for f in m&r if f not in same)
removed=sorted(m-r); new=sorted((r-m)|{'docs/FROM-MIPS.md'})
def grp(lst):
    g=OrderedDict()
    for f in lst: g.setdefault(os.path.dirname(f) or '.',[]).append(os.path.basename(f))
    return '\n'.join(f'- `{d}/`: '+', '.join(f'`{x}`' for x in v) for d,v in g.items())
txt=f'''# What came from the MIPS edition

Source: `ars2323/hallym-mips-simulator`, tag `v2.8.0`
(commit `35be23de3bc765b219ea6669ed3c83f625d0d34b`), its `electron/` directory.  Until 1.0.0
this list was made against v2.7.1 (commit `09a3066974602dcbeb78287428b342e401104a6a`); 1.0.0
took 2.8.0's first screen, and the list is made against that now.
**Every file kept its path and name** (`electron/<same path>`), so a fix found in one
edition's UI can be carried to the other as it is.  Generated by comparing the two trees
(SHA-256 of each file); regenerate after changing what is carried over.

| | files |
|---|---|
| unchanged (byte for byte) | {len(same)} |
| changed for RISC-V | {len(changed)} |
| not brought (MIPS-only, or held back this round) | {len(removed)} |
| new in the RISC-V edition | {len(new)} |

Also brought, outside `electron/`: the MIPS edition's workflows, changed for this app where
they are in `.github/workflows/` (`electron.yml`, `release-check.yml`, `mutants.yml`), and its
seven release rules, merged into the repository's `CLAUDE.md`.  Each edition's screenshots
(`docs/screens/`) are its own and not compared.  Made by `tools/from-mips.py`.

## Unchanged

{grp(same)}

## Changed for RISC-V

{grp(changed)}

## Not brought

MIPS-only: the N-API addon (`native/`; the engine is RARS in a JVM), the simulator worker
(`src/sim/worker.ts`; the engine took its place), every `.hmx` file (the executable image
export), SPIM's syntax table, error parsing and goldens, the tests of SPIM's own machine
options, the MIPS release notes, the design mockups and the design studies of the old
photo first screen (`docs/start-variants/`: that screen is gone from both editions).

{grp(removed)}

## New

{grp(new)}
'''
open(os.path.join(R,'docs/FROM-MIPS.md'),'w').write(txt)
print(len(same),len(changed),len(removed),len(new))
