/* Writes src/core/op-table.ts from RARS's own source at its pinned commit
   ($RARS_HOME/src, probe/setup.sh): the editor colours a word as an
   instruction exactly when the assembler accepts it as one.

     node tools/gen-op-table.ts            write it
     node tools/gen-op-table.ts --check    exit 1 if it is not up to date

   - basic: the mnemonic of every rars/riscv/instructions/*.java (the first
     word of the example its constructor gives: super("addi t1,t2,-100", ...))
   - pseudo: the first word of every line of PseudoOps.txt
   - directives: rars/assembler/Directives.java's, in its order
   (The MIPS edition's gen-op-table.ts read SPIM's CPU/op.h the same way.) */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..');
const rarsHome = process.env.RARS_HOME ?? path.join(os.homedir(), '.cache', 'hallym-riscv', 'rars');
const src = path.join(rarsHome, 'src', 'src');
const out = path.join(root, 'src/core/op-table.ts');

const dir = path.join(src, 'rars/riscv/instructions');
const basic = new Set<string>();
for (const f of readdirSync(dir).filter((n) => n.endsWith('.java'))) {
  const m = /super\(\s*"([^\s"]+)/.exec(readFileSync(path.join(dir, f), 'utf8'));
  if (m) basic.add(m[1].toLowerCase());
}
const pseudo = new Set<string>();
for (const line of readFileSync(path.join(src, 'PseudoOps.txt'), 'utf8').split('\n')) {
  if (/^\s*(#|$)/.test(line)) continue;
  pseudo.add(line.trim().split(/[\s;]+/)[0].toLowerCase());
}
for (const b of basic) pseudo.delete(b);
const directives = [...readFileSync(path.join(src, 'rars/assembler/Directives.java'), 'utf8')
  .matchAll(/new Directives\("(\.[\w]+)"/g)].map((m) => m[1]);

const rows = [
  ...[...basic].sort().map((n) => `  ['${n}', 'basic'],`),
  ...[...pseudo].sort().map((n) => `  ['${n}', 'pseudo'],`),
  ...directives.map((n) => `  ['${n}', 'directive'],`),
];
const text = `/* The assembler's own keyword table: every instruction (basic and pseudo)
   and directive RARS v1.6 accepts, taken from its source at the pinned
   commit 7acf3254 -- rars/riscv/instructions/*.java (basic), PseudoOps.txt
   (pseudo) and rars/assembler/Directives.java.  The editor colours a word
   as an instruction exactly when the assembler accepts it as one.
   Generated by tools/gen-op-table.ts; do not edit by hand.  (The MIPS
   edition's op-table.ts came from SPIM's CPU/op.h the same way.) */

export type OpType = 'basic' | 'pseudo' | 'directive';

export const OP_TABLE: readonly (readonly [string, OpType])[] = [
${rows.join('\n')}
];
`;
if (process.argv.includes('--check')) {
  if (readFileSync(out, 'utf8') !== text) { console.error('src/core/op-table.ts is not what RARS says: node tools/gen-op-table.ts'); process.exit(1); }
  console.log(`op-table.ts up to date: ${basic.size} basic, ${pseudo.size} pseudo, ${directives.length} directives`);
} else {
  writeFileSync(out, text);
  console.log(`wrote src/core/op-table.ts: ${basic.size} basic, ${pseudo.size} pseudo, ${directives.length} directives`);
}
